# system base
application:
  name: shopping-admin-consumer
  port: 8083

# logs
zap:
  log-dir: ./tmp/logs/
  log-level: DebugLevel

# ncaos
nacos:
  username: nacos
  password: nacos
  config:
    group: golang_dev
    server-addr: 127.0.0.1
    port: 8848
    namespace: cc27da66-48c4-4286-8a25-e9f4c72a892f
    prefix: shopping-admin-consumer
    data-id: shopping-admin-consumer
    file-extension: json
  log-dir: ./tmp/nacos/
  cache-dir: ./tmp/nacos/cache