// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "杨大琼",
            "url": "http://localhost",
            "email": "826422592@qq.com"
        },
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/order": {
            "post": {
                "description": "主要用于统一下单",
                "tags": [
                    "订单管理"
                ],
                "summary": "统一下单",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "应用参数",
                        "name": "createOder",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/order.CreateOrderParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "主要用于订单删除",
                "tags": [
                    "订单管理"
                ],
                "summary": "删除订单",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "删除参数",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/order/findById/{id}": {
            "get": {
                "description": "根据id查询订单内容详情",
                "tags": [
                    "订单管理"
                ],
                "summary": "根据id查询订单内容详情",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "订单id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/order/findByParams": {
            "post": {
                "description": "根据订单参数查询订单信息",
                "tags": [
                    "订单管理"
                ],
                "summary": "根据订单参数查询订单信息",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "查询参数",
                        "name": "pageInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/order.OrderParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/order/findPageList": {
            "post": {
                "description": "主要用于查询订单分页列表",
                "tags": [
                    "订单管理"
                ],
                "summary": "订单分页列表",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "查询参数",
                        "name": "pageInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Request-order_OrderParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/Pager"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "list": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/order.OrderListVo"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/order/m": {
            "delete": {
                "description": "主要用于订单删除",
                "tags": [
                    "订单管理-移动端"
                ],
                "summary": "删除订单",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "删除参数",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/order/m/findPageList": {
            "post": {
                "description": "主要用于查询订单分页列表",
                "tags": [
                    "订单管理-移动端"
                ],
                "summary": "订单分页列表-移动端",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "查询参数",
                        "name": "pageInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Request-order_OrderMobileParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/Pager"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "list": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/order.OrderListVo"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/order/pay": {
            "post": {
                "description": "主要用于订单支付",
                "tags": [
                    "订单管理"
                ],
                "summary": "订单支付",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "订单支付参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/order.PayOrderParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/order/statistics": {
            "get": {
                "description": "订单统计",
                "tags": [
                    "订单管理"
                ],
                "summary": "订单统计",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/pay/updatePayPwd": {
            "post": {
                "description": "主要用于设置支付密码",
                "tags": [
                    "支付相关"
                ],
                "summary": "设置支付密码",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "支付参数设置",
                        "name": "pwdParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/order.SetPayPwdParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/pocketMoney/create/{amount}": {
            "get": {
                "description": "主要用于余额充值",
                "tags": [
                    "零钱管理"
                ],
                "summary": "余额充值",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "金额",
                        "name": "amount",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/pocketMoney/findById/{id}": {
            "get": {
                "description": "主要用于根据id查询详情",
                "tags": [
                    "模板管理-运费模板"
                ],
                "summary": "根据id查询详情",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "模板id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/order.FreightTemplates"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/pocketMoney/findPageList": {
            "post": {
                "description": "主要用于查询充值记录",
                "tags": [
                    "零钱管理"
                ],
                "summary": "充值记录",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "查询参数",
                        "name": "pageInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/order.PocketMoneyPageAuthQuery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/pocketMoney/getBalance": {
            "get": {
                "description": "主要用于查询零钱余额",
                "tags": [
                    "零钱管理"
                ],
                "summary": "查询零钱余额",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/templates": {
            "put": {
                "description": "主要用于用户进行模板修改",
                "tags": [
                    "模板管理-运费模板"
                ],
                "summary": "模板修改",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "模板参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/order.FreightTemplates"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            },
            "post": {
                "description": "主要用于用户进行模板添加",
                "tags": [
                    "模板管理-运费模板"
                ],
                "summary": "模板添加",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "模板新增参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/order.FreightTemplates"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "主要用于用户进行模板删除",
                "tags": [
                    "模板管理-运费模板"
                ],
                "summary": "模板删除",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "模板id集合",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/templates/findById/{id}": {
            "get": {
                "description": "主要用于模板详情查询",
                "tags": [
                    "模板管理-运费模板"
                ],
                "summary": "根据id模板详情查询",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "模板id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/templates/findPageList": {
            "post": {
                "description": "主要用于模板分页列表查询",
                "tags": [
                    "模板管理-运费模板"
                ],
                "summary": "模板分页列表查询",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "查询参数",
                        "name": "pageInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/order.FreightTemplatesPageAuthQuery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/Pager"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "list": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/order.FreightTemplates"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/templatesFree": {
            "put": {
                "description": "主要用于用户进行模板免邮修改",
                "tags": [
                    "模板管理-免邮"
                ],
                "summary": "模板免邮修改",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "模板免邮参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/order.FreightTemplatesFree"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            },
            "post": {
                "description": "主要用于用户进行模板免邮添加",
                "tags": [
                    "模板管理-免邮"
                ],
                "summary": "模板免邮添加",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "模板免邮新增参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/order.FreightTemplatesFree"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "主要用于用户进行模板免邮删除",
                "tags": [
                    "模板管理-免邮"
                ],
                "summary": "模板免邮删除",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "模板免邮id集合",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/templatesFree/findById/{id}": {
            "get": {
                "description": "主要用于模板免邮详情查询",
                "tags": [
                    "模板管理-免邮"
                ],
                "summary": "根据id模板免邮详情查询",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "模板免邮id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/order.FreightTemplatesFree"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/templatesFree/findPageList": {
            "post": {
                "description": "主要用于模板免邮分页列表查询",
                "tags": [
                    "模板管理-免邮"
                ],
                "summary": "模板免邮分页列表查询",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "查询参数",
                        "name": "pageInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Request-any"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/Pager"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "list": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/order.FreightTemplatesFree"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/templatesRegion": {
            "put": {
                "description": "主要用于用户进行模板区域运费修改",
                "tags": [
                    "模板管理-区域运费"
                ],
                "summary": "模板区域运费修改",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "模板区域运费参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/order.FreightTemplatesRegion"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            },
            "post": {
                "description": "主要用于用户进行模板区域运费添加",
                "tags": [
                    "模板管理-区域运费"
                ],
                "summary": "模板区域运费添加",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "模板区域运费新增参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/order.FreightTemplatesRegion"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "主要用于用户进行模板区域运费删除",
                "tags": [
                    "模板管理-区域运费"
                ],
                "summary": "模板区域运费删除",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "模板区域运费id集合",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/templatesRegion/findById/{id}": {
            "get": {
                "description": "主要用于模板区域运费详情查询",
                "tags": [
                    "模板管理-区域运费"
                ],
                "summary": "根据id模板区域运费详情查询",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "模板区域运费id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/order.FreightTemplatesRegion"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/templatesRegion/findPageList": {
            "post": {
                "description": "主要用于模板区域运费分页列表查询",
                "tags": [
                    "模板管理-区域运费"
                ],
                "summary": "模板区域运费分页列表查询",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "查询参数",
                        "name": "pageInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Request-any"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/Pager"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "list": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/order.FreightTemplatesRegion"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/templatesUndelivered": {
            "put": {
                "description": "主要用于用户进行模板不送达修改",
                "tags": [
                    "模板管理-不送达"
                ],
                "summary": "模板不送达修改",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "模板不送达参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/order.FreightTemplatesUndelivered"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            },
            "post": {
                "description": "主要用于用户进行模板不送达添加",
                "tags": [
                    "模板管理-不送达"
                ],
                "summary": "模板不送达添加",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "模板不送达新增参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/order.FreightTemplatesUndelivered"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "主要用于用户进行模板不送达删除",
                "tags": [
                    "模板管理-不送达"
                ],
                "summary": "模板不送达删除",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "模板不送达id集合",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/templatesUndelivered/findById/{id}": {
            "get": {
                "description": "主要用于模板不送达详情查询",
                "tags": [
                    "模板管理-不送达"
                ],
                "summary": "根据id模板不送达详情查询",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "模板不送达id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/order.FreightTemplatesUndelivered"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/templatesUndelivered/findPageList": {
            "post": {
                "description": "主要用于模板不送达分页列表查询",
                "tags": [
                    "模板管理-不送达"
                ],
                "summary": "模板不送达分页列表查询",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "查询参数",
                        "name": "pageInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Request-any"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/Pager"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "list": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/order.FreightTemplatesUndelivered"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/wechat/closeOrder/{tradeNo}": {
            "get": {
                "description": "主要用于关闭订单",
                "tags": [
                    "微信支付"
                ],
                "summary": "关闭订单",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "订单号",
                        "name": "tradeNo",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/wechat/findOrderByTradeNo/{tradeNo}": {
            "get": {
                "description": "主要用于订单查询",
                "tags": [
                    "微信支付"
                ],
                "summary": "订单支付查询",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "订单号",
                        "name": "tradeNo",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/wechat/notify/{confId}": {
            "post": {
                "description": "主要用于微信订单支付成功回调",
                "tags": [
                    "微信支付"
                ],
                "summary": "微信支付成功回调",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/wechat/weChatRefunds": {
            "get": {
                "description": "主要用于申请退款",
                "tags": [
                    "微信支付"
                ],
                "summary": "申请退款",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Pager": {
            "description": "Pager 请求参数统一封装",
            "type": "object",
            "properties": {
                "list": {
                    "description": "列表"
                },
                "pageIndex": {
                    "description": "分页索引",
                    "type": "integer"
                },
                "pageNum": {
                    "description": "分页数",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "分页长度",
                    "type": "integer"
                },
                "totalCount": {
                    "description": "数据长度",
                    "type": "integer"
                }
            }
        },
        "Request-any": {
            "type": "object",
            "required": [
                "pageIndex",
                "pageSize"
            ],
            "properties": {
                "pageIndex": {
                    "description": "分页索引",
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "pageSize": {
                    "description": "分页长度",
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 10,
                    "example": 10
                },
                "params": {
                    "description": "请求查询参数"
                }
            }
        },
        "Request-order_OrderMobileParams": {
            "type": "object",
            "required": [
                "pageIndex",
                "pageSize"
            ],
            "properties": {
                "pageIndex": {
                    "description": "分页索引",
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "pageSize": {
                    "description": "分页长度",
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 10,
                    "example": 10
                },
                "params": {
                    "description": "请求查询参数",
                    "allOf": [
                        {
                            "$ref": "#/definitions/order.OrderMobileParams"
                        }
                    ]
                }
            }
        },
        "Request-order_OrderParams": {
            "type": "object",
            "required": [
                "pageIndex",
                "pageSize"
            ],
            "properties": {
                "pageIndex": {
                    "description": "分页索引",
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "pageSize": {
                    "description": "分页长度",
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 10,
                    "example": 10
                },
                "params": {
                    "description": "请求查询参数",
                    "allOf": [
                        {
                            "$ref": "#/definitions/order.OrderParams"
                        }
                    ]
                }
            }
        },
        "Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "结果状态码",
                    "type": "integer",
                    "default": 0
                },
                "data": {
                    "description": "结果"
                },
                "msg": {
                    "description": "状态信息",
                    "type": "string",
                    "default": "请求失败"
                }
            }
        },
        "order.CreateOrderParams": {
            "type": "object"
        },
        "order.FreightTemplates": {
            "type": "object",
            "required": [
                "appoint",
                "billingMethods",
                "name",
                "noDelivery"
            ],
            "properties": {
                "appoint": {
                    "description": "指定包邮(0:包邮 1:不包邮)",
                    "type": "integer",
                    "default": 0,
                    "maximum": 1,
                    "minimum": 0
                },
                "billingMethods": {
                    "description": "计费方式 1、DHL快递收费 2 ups快递收费 3、FEDEX快递收费 4、EMS快递收费",
                    "type": "integer",
                    "maximum": 4,
                    "minimum": 1
                },
                "name": {
                    "description": "模板名称",
                    "type": "string"
                },
                "noDelivery": {
                    "description": "指定不送达 (0:送达 1:不送达)",
                    "type": "integer",
                    "default": 0,
                    "maximum": 1,
                    "minimum": 0
                },
                "sortBy": {
                    "description": "排序",
                    "type": "integer"
                },
                "tempId": {
                    "description": "模板id(新增时不传值，修改时必须传值)",
                    "type": "string"
                }
            }
        },
        "order.FreightTemplatesFree": {
            "type": "object",
            "required": [
                "areaCode",
                "billingMethods",
                "price",
                "quantity"
            ],
            "properties": {
                "areaCode": {
                    "description": "地区code(省或者城市)",
                    "type": "string"
                },
                "billingMethods": {
                    "description": "计费方式",
                    "type": "integer"
                },
                "freeId": {
                    "description": "包邮id",
                    "type": "string"
                },
                "price": {
                    "description": "包邮金额",
                    "type": "number"
                },
                "quantity": {
                    "description": "包邮件数",
                    "type": "integer"
                }
            }
        },
        "order.FreightTemplatesPageAuthQuery": {
            "type": "object",
            "required": [
                "pageIndex",
                "pageSize"
            ],
            "properties": {
                "pageIndex": {
                    "description": "分页索引",
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "pageSize": {
                    "description": "分页长度",
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 10,
                    "example": 10
                },
                "params": {
                    "description": "查询参数",
                    "allOf": [
                        {
                            "$ref": "#/definitions/order.FreightTemplatesPageAuthQuery_QueryParams"
                        }
                    ]
                }
            }
        },
        "order.FreightTemplatesPageAuthQuery_QueryParams": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "order.FreightTemplatesRegion": {
            "type": "object",
            "required": [
                "areaCode",
                "billingMethods",
                "continued",
                "continuedPrice",
                "first",
                "firstPrice",
                "tempId"
            ],
            "properties": {
                "areaCode": {
                    "description": "地区编码(包含省和市)",
                    "type": "string"
                },
                "billingMethods": {
                    "description": "计费方式",
                    "type": "integer"
                },
                "continued": {
                    "description": "续件",
                    "type": "integer"
                },
                "continuedPrice": {
                    "description": "续件价格",
                    "type": "number"
                },
                "first": {
                    "description": "首件",
                    "type": "integer"
                },
                "firstPrice": {
                    "description": "首件运费",
                    "type": "number"
                },
                "regionId": {
                    "description": "区域运费id",
                    "type": "string"
                },
                "tempId": {
                    "description": "模板id",
                    "type": "string"
                }
            }
        },
        "order.FreightTemplatesUndelivered": {
            "type": "object",
            "required": [
                "areaCode",
                "tempId"
            ],
            "properties": {
                "areaCode": {
                    "description": "地区编码(包含省和市",
                    "type": "string"
                },
                "tempId": {
                    "description": "模板id",
                    "type": "string"
                },
                "undeliveredId": {
                    "description": "不送达id",
                    "type": "string"
                }
            }
        },
        "order.OrderListVo": {
            "type": "object",
            "properties": {
                "confId": {
                    "description": "配置id",
                    "type": "string"
                },
                "confIdName": {
                    "description": "配置id",
                    "type": "string"
                },
                "createBy": {
                    "description": "创建人",
                    "type": "string"
                },
                "createTime": {
                    "description": "创建时间",
                    "type": "string"
                },
                "delStatus": {
                    "description": "删除状态",
                    "type": "boolean"
                },
                "freightPrice": {
                    "description": "运费金额",
                    "type": "number"
                },
                "orderId": {
                    "description": "订单id",
                    "type": "string"
                },
                "orderNo": {
                    "description": "订单号",
                    "type": "string"
                },
                "parentId": {
                    "description": "父类订单id",
                    "type": "string"
                },
                "payPrice": {
                    "description": "实际支付金额",
                    "type": "number"
                },
                "payStatus": {
                    "description": "支付状态",
                    "type": "integer"
                },
                "payStatusName": {
                    "description": "支付状态",
                    "type": "string"
                },
                "payTime": {
                    "description": "支付时间",
                    "type": "string"
                },
                "payType": {
                    "description": "支付类型(1:直接支付 2:余额支付)",
                    "type": "integer"
                },
                "payTypeName": {
                    "description": "支付类型名称",
                    "type": "string"
                },
                "realName": {
                    "description": "用户姓名",
                    "type": "string"
                },
                "status": {
                    "description": "订单状态(1:待付款[默认] 2:待发货 3:已发货 4:待收货 5:已收货 6:待评价 7:订单关闭)",
                    "type": "integer"
                },
                "statusName": {
                    "description": "状态名称",
                    "type": "string"
                },
                "totalPostage": {
                    "description": "邮费",
                    "type": "number"
                },
                "totalPrice": {
                    "description": "订单总价",
                    "type": "number"
                },
                "totalQuantity": {
                    "description": "订单商品总数",
                    "type": "integer"
                },
                "tradeNo": {
                    "description": "下单号",
                    "type": "string"
                },
                "tradeType": {
                    "description": "交易类型(1:微信 2:支付宝)",
                    "type": "integer"
                },
                "tradeTypeName": {
                    "description": "交易类型名称",
                    "type": "string"
                },
                "updateBy": {
                    "description": "修改人",
                    "type": "string"
                },
                "updateTime": {
                    "description": "修改时间",
                    "type": "string"
                },
                "userAddress": {
                    "description": "详细地址",
                    "type": "string"
                },
                "userPhone": {
                    "description": "用户电话",
                    "type": "string"
                }
            }
        },
        "order.OrderMobileParams": {
            "type": "object",
            "properties": {
                "findType": {
                    "description": "查询类型 1:个人订单查询 2:管理员订单查询",
                    "type": "integer"
                },
                "orderNo": {
                    "description": "订单号",
                    "type": "string"
                }
            }
        },
        "order.OrderParams": {
            "type": "object",
            "properties": {
                "orderNo": {
                    "description": "订单号",
                    "type": "string"
                },
                "payStatus": {
                    "description": "订单状态(1:待付款[默认] 2:待发货 3:已发货 4:待收货 5:已收货 6:待评价 7:订单关闭)",
                    "type": "integer"
                },
                "tradeNo": {
                    "description": "下单号",
                    "type": "string"
                },
                "userPhone": {
                    "description": "下单电话号码",
                    "type": "string"
                }
            }
        },
        "order.PayOrderParam": {
            "type": "object",
            "required": [
                "orderId",
                "payMark",
                "payType",
                "tradeType"
            ],
            "properties": {
                "orderId": {
                    "description": "订单id",
                    "type": "string"
                },
                "payMark": {
                    "description": "支付标识必传",
                    "type": "string"
                },
                "payPwd": {
                    "description": "支付密码[余额支付时必传]",
                    "type": "string"
                },
                "payType": {
                    "description": "支付类型(1:微信公众号 2:微信小程序 3:支付宝支付)",
                    "type": "integer"
                },
                "tradeType": {
                    "description": "交易类型(1:余额 2:微信  3:支付宝)",
                    "type": "integer"
                }
            }
        },
        "order.PocketMoneyPageAuthQuery": {
            "type": "object",
            "required": [
                "pageIndex",
                "pageSize"
            ],
            "properties": {
                "pageIndex": {
                    "description": "分页索引",
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "pageSize": {
                    "description": "分页长度",
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 10,
                    "example": 10
                },
                "params": {
                    "description": "查询参数",
                    "allOf": [
                        {
                            "$ref": "#/definitions/order.PocketMoneyPageAuthQuery_QueryParams"
                        }
                    ]
                }
            }
        },
        "order.PocketMoneyPageAuthQuery_QueryParams": {
            "type": "object",
            "properties": {
                "payType": {
                    "description": "支付类型",
                    "type": "string"
                },
                "rechargeId": {
                    "description": "充值订单id",
                    "type": "string"
                }
            }
        },
        "order.SetPayPwdParam": {
            "type": "object",
            "required": [
                "payPwd",
                "phone",
                "verifyCode"
            ],
            "properties": {
                "payPwd": {
                    "description": "密码",
                    "type": "string"
                },
                "phone": {
                    "description": "收i手机号",
                    "type": "string"
                },
                "verifyCode": {
                    "description": "验证码",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/api/order",
	Schemes:          []string{},
	Title:            "订单服务提供者文档",
	Description:      "swagger go API文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
