// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "杨大琼",
            "url": "http://localhost",
            "email": "826422592@qq.com"
        },
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ad/findById/{id}": {
            "get": {
                "description": "根据id查询广告内容详情",
                "tags": [
                    "广告管理"
                ],
                "summary": "根据id查询广告内容详情",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "广告id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/ad/findList/{type}/{position}": {
            "get": {
                "description": "主要用于获取广告信息",
                "tags": [
                    "广告管理"
                ],
                "summary": "获取广告信息",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "广告类型[1:轮播图广告,2:单张图片]",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "广告位置[1:首页,2:列表,3:详情页]",
                        "name": "position",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/business": {
            "put": {
                "description": "主要用于商家修改",
                "tags": [
                    "商家管理"
                ],
                "summary": "修改商家",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "修改商家参数",
                        "name": "business",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/shopping_client.Business"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            },
            "post": {
                "description": "主要用于商家新增",
                "tags": [
                    "商家管理"
                ],
                "summary": "创建商家",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "新增商家参数",
                        "name": "business",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/shopping_client.Business"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "主要用于商家删除",
                "tags": [
                    "商家管理"
                ],
                "summary": "删除商家",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "删除参数",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/business/findById/{id}": {
            "get": {
                "description": "根据id查询商家内容详情",
                "tags": [
                    "商家管理"
                ],
                "summary": "根据id查询商家内容详情",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商家id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/business/findPageList": {
            "post": {
                "description": "主要用于查询商家分页列表",
                "tags": [
                    "商家管理"
                ],
                "summary": "商家分页列表",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "查询参数",
                        "name": "pageInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Request-shopping_client_BusinessParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/businessCircle": {
            "delete": {
                "description": "主要用于商圈删除",
                "tags": [
                    "商圈管理"
                ],
                "summary": "删除商圈",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "商圈是删除参数",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/businessCircle/findById/{id}": {
            "get": {
                "description": "根据id查询商圈内容详情",
                "tags": [
                    "商圈管理"
                ],
                "summary": "根据id查询商圈内容详情",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商圈id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/businessCircle/findPageList": {
            "post": {
                "description": "主要用于查询商圈分页列表",
                "tags": [
                    "商圈管理"
                ],
                "summary": "商圈分页列表",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "查询参数",
                        "name": "pageInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Request-shopping_client_BusinessCircleParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/businessStore": {
            "delete": {
                "description": "主要用于商家门店删除",
                "tags": [
                    "商家门店管理"
                ],
                "summary": "删除商家门店",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "商家门店是删除参数",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/businessStore/findById/{id}": {
            "get": {
                "description": "根据id查询商家门店内容详情",
                "tags": [
                    "商家门店管理"
                ],
                "summary": "根据id查询商家门店内容详情",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商家门店id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/businessStore/findPageList": {
            "post": {
                "description": "主要用于查询商家门店分页列表",
                "tags": [
                    "商家门店管理"
                ],
                "summary": "商家门店分页列表",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "查询参数",
                        "name": "pageInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Request-shopping_client_BusinessStoreParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/cart/add": {
            "post": {
                "description": "主要用于查看购物车列表",
                "tags": [
                    "购物车"
                ],
                "summary": "购物车列表",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "添加参数",
                        "name": "addCartParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/shopping_client.Cart"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/cart/changeQuantity/{cartId}/{quantity}": {
            "get": {
                "description": "主要用于修改购物车数量",
                "tags": [
                    "购物车"
                ],
                "summary": "修改购物车数量",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "购物车id",
                        "name": "cartId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品数量id",
                        "name": "quantity",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/cart/delete": {
            "delete": {
                "description": "主要用于购物车商品删除",
                "tags": [
                    "购物车"
                ],
                "summary": "根据商品id购删除购物车商品",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "删除参数",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/cart/findCount": {
            "get": {
                "description": "主要用于查询用户的购物车数量",
                "tags": [
                    "购物车"
                ],
                "summary": "查询用户的购物车数量",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/cart/findPageList": {
            "post": {
                "description": "主要用于查看购物车列表",
                "tags": [
                    "购物车"
                ],
                "summary": "购物车列表",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "查询参数",
                        "name": "pageInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/shopping_client.CartPageAuthQuery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/franchisee": {
            "put": {
                "description": "主要用于商家入住修改",
                "tags": [
                    "商家入住管理"
                ],
                "summary": "修改商家入住",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "修改商家入住参数",
                        "name": "franchisee",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/shopping_client.BusinessFranchisee"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            },
            "post": {
                "description": "主要用于商家入住新增",
                "tags": [
                    "商家入住管理"
                ],
                "summary": "创建商家入住",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "新增商家入住参数",
                        "name": "franchisee",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/shopping_client.BusinessFranchisee"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "主要用于商家入住删除",
                "tags": [
                    "商家入住管理"
                ],
                "summary": "删除商家入住",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "删除参数",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/franchisee/findById/{id}": {
            "get": {
                "description": "根据id查询商家入住内容详情",
                "tags": [
                    "商家入住管理"
                ],
                "summary": "根据id查询商家入住内容详情",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商家入住id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/franchisee/findPageList": {
            "post": {
                "description": "主要用于查询商家入住分页列表",
                "tags": [
                    "商家入住管理"
                ],
                "summary": "商家入住分页列表",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "查询参数",
                        "name": "pageInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Request-shopping_client_BusinessFranchiseeParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/product/categoryByParentId/{parentId}": {
            "get": {
                "description": "主要用于根据商品父id查询下级分类",
                "tags": [
                    "商品接口"
                ],
                "summary": "根据商品父id查询下级分类",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "分类父id",
                        "name": "parentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/product/categoryTreeByParentId/{parentId}": {
            "get": {
                "description": "主要用于根据商品父id查询所有子分类",
                "tags": [
                    "商品接口"
                ],
                "summary": "根据商品父id查询所有子分类【树形结构】",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "分类父id",
                        "name": "parentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/product/findById/{productId}": {
            "get": {
                "description": "主要用于商品详情查询",
                "tags": [
                    "商品接口"
                ],
                "summary": "商品详情",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品id",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/product/findPageList": {
            "post": {
                "description": "主要用于商品分页列表",
                "tags": [
                    "商品接口"
                ],
                "summary": "商品分页列表",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer token",
                        "description": "授权令牌",
                        "name": "accessToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/shopping_client.ProductPageAuthQuery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "请求异常",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Request-shopping_client_BusinessCircleParam": {
            "type": "object",
            "required": [
                "pageIndex",
                "pageSize"
            ],
            "properties": {
                "pageIndex": {
                    "description": "分页索引",
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "pageSize": {
                    "description": "分页长度",
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 10,
                    "example": 10
                },
                "params": {
                    "description": "请求查询参数",
                    "allOf": [
                        {
                            "$ref": "#/definitions/shopping_client.BusinessCircleParam"
                        }
                    ]
                }
            }
        },
        "Request-shopping_client_BusinessFranchiseeParam": {
            "type": "object",
            "required": [
                "pageIndex",
                "pageSize"
            ],
            "properties": {
                "pageIndex": {
                    "description": "分页索引",
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "pageSize": {
                    "description": "分页长度",
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 10,
                    "example": 10
                },
                "params": {
                    "description": "请求查询参数",
                    "allOf": [
                        {
                            "$ref": "#/definitions/shopping_client.BusinessFranchiseeParam"
                        }
                    ]
                }
            }
        },
        "Request-shopping_client_BusinessParam": {
            "type": "object",
            "required": [
                "pageIndex",
                "pageSize"
            ],
            "properties": {
                "pageIndex": {
                    "description": "分页索引",
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "pageSize": {
                    "description": "分页长度",
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 10,
                    "example": 10
                },
                "params": {
                    "description": "请求查询参数",
                    "allOf": [
                        {
                            "$ref": "#/definitions/shopping_client.BusinessParam"
                        }
                    ]
                }
            }
        },
        "Request-shopping_client_BusinessStoreParam": {
            "type": "object",
            "required": [
                "pageIndex",
                "pageSize"
            ],
            "properties": {
                "pageIndex": {
                    "description": "分页索引",
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "pageSize": {
                    "description": "分页长度",
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 10,
                    "example": 10
                },
                "params": {
                    "description": "请求查询参数",
                    "allOf": [
                        {
                            "$ref": "#/definitions/shopping_client.BusinessStoreParam"
                        }
                    ]
                }
            }
        },
        "Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "结果状态码",
                    "type": "integer",
                    "default": 0
                },
                "data": {
                    "description": "结果"
                },
                "msg": {
                    "description": "状态信息",
                    "type": "string",
                    "default": "请求失败"
                }
            }
        },
        "shopping_client.Business": {
            "type": "object"
        },
        "shopping_client.BusinessCircleParam": {
            "type": "object"
        },
        "shopping_client.BusinessFranchisee": {
            "type": "object"
        },
        "shopping_client.BusinessFranchiseeParam": {
            "type": "object"
        },
        "shopping_client.BusinessParam": {
            "type": "object"
        },
        "shopping_client.BusinessStoreParam": {
            "type": "object"
        },
        "shopping_client.Cart": {
            "type": "object",
            "required": [
                "image",
                "productAttrUnique",
                "productId",
                "quantity",
                "specType"
            ],
            "properties": {
                "bargainId": {
                    "description": "砍价id",
                    "type": "string"
                },
                "cartId": {
                    "description": "购物车id",
                    "type": "string"
                },
                "groupBuyId": {
                    "description": "拼团id",
                    "type": "string"
                },
                "image": {
                    "description": "商品图片",
                    "type": "string"
                },
                "presaleId": {
                    "description": "预售商品id",
                    "type": "string"
                },
                "productAttrUnique": {
                    "description": "商品属性",
                    "type": "string"
                },
                "productId": {
                    "description": "商品id",
                    "type": "string"
                },
                "quantity": {
                    "description": "商品数量",
                    "type": "integer"
                },
                "seckillId": {
                    "description": "秒杀商品id",
                    "type": "string"
                },
                "specType": {
                    "description": "规格(1:单规格 2:多规格)",
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "type": "integer"
                }
            }
        },
        "shopping_client.CartPageAuthQuery": {
            "type": "object",
            "properties": {
                "pageIndex": {
                    "description": "分页索引",
                    "type": "integer",
                    "default": 1
                },
                "pageSize": {
                    "description": "分页长度",
                    "type": "integer",
                    "default": 10
                }
            }
        },
        "shopping_client.ProductPageAuthQuery": {
            "type": "object",
            "properties": {
                "pageIndex": {
                    "description": "分页索引",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "分页长度",
                    "type": "integer"
                },
                "params": {
                    "description": "查询参数",
                    "allOf": [
                        {
                            "$ref": "#/definitions/shopping_client.ProductPageAuthQuery_QueryParams"
                        }
                    ]
                }
            }
        },
        "shopping_client.ProductPageAuthQuery_QueryParams": {
            "type": "object",
            "properties": {
                "keyword": {
                    "description": "关键词",
                    "type": "string"
                },
                "productName": {
                    "description": "商品名称",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/api/shopping/client",
	Schemes:          []string{},
	Title:            "客户端接口文档",
	Description:      "swagger go API文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
